### ISSUE TITLE
repo addon.xml file

### ISSUE THREAD

**Issue by mgonzales71** [reddit-reaper/Addons#1]
Not sure why but your repo doesn't want to work with Kodi (crashes latest nightlies Win x64)

Thought I had figured it out but then I wasn't sure.

Does Kodi expect addon.xml or addons.xml for repos?  (I think it's addons.xml)

**Comment by mgonzales71** [comment]
yea after checking it seems that is's addons.xml 

try updating your repos's addon.xml file to point to (and rename on github) addons.xml

Hope that works

**Comment by reddit-reaper** [comment]
yeah i saw that as well on leia, didnt realize it was because i had it named wrong lol fixing thanks
